import type { Metadata } from 'next'
import { Aclonica, Geist, Geist_Mono, Inter, Inter_Tight, Oleo_Script, Sansita, Sonsie_One } from 'next/font/google'
import './globals.css'
import { Provider } from './providers/Provider'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
})

const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})
const interTight = Inter_Tight({
	variable: '--font-inter-tight',
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})
const aclonica = Aclonica({
	variable: '--font-aclonica',
	subsets: ['latin'],
	weight: '400'
})
const sonsie = Sonsie_One({
	variable: '--font-sonsie',
	subsets: ['latin'],
	weight: '400'
})
const oleo = Oleo_Script({
	variable: '--font-oleo',
	subsets: ['latin'],
	weight: '400'
})
const sansita = Sansita({
	variable: '--font-sansita',
	subsets: ['latin'],
	weight: ['400', '700', '800', '900']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${aclonica.variable} ${sonsie.variable} ${oleo.variable} ${sansita.variable} ${inter.variable} ${interTight.variable} antialiased flex flex-col w-full h-full min-h-screen p-8 gap-8`}
			>
				<Provider>{children}</Provider>
			</body>
		</html>
	)
}
